GET http://localhost:5000/users

###
GET http://localhost:5000/users/63da19d79c399ac541f19a70

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"aji",
    "email":"aji@gmail.com",
    "gender":"Male"
}