GET http://localhost:5000/users

###
GET http://localhost:5000/users/63da19d79c399ac541f19a70

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"budi",
    "email":"uhuy@gmail.com",
    "gender":"male"
}

###
PATCH http://localhost:5000/users/63da19d79c399ac541f19a70
Content-Type: application/json

{
    "name":"aldo",
    "email":"aaalll@gmail.com",
    "gender":"Male"
}

###
DELETE http://localhost:5000/users/63da1b799c399ac541f19a73
    